apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-app
      track: stable
  template:
    metadata:
      labels:
        app: nginx-app
        track: stable
    spec:
      containers:
      - name: stable-app
        image: alihussainia/app:stable 
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources: {}
